=== SoraGrace/JavaLearning/TestUnit/src/com/fja/xml/xsd/bookshelf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.asdmd177.org/bookshelf"
	xmlns="http://www.w3school.com.cn"
	elementFormDefault="qualified">

	<xs:element name="书架">
		<!-- 是复杂类型(element) -->
		<xs:complexType>
			<!-- 顺序指示器，规定了子元素的书写顺序 -->
			<xs:sequence>
				<!-- maxOccurs、minOccurs出现频率指示器，指定出现的次数，unbounded表示不限次数。不写默认出现一次 -->
				<xs:element name="书" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<!-- type 文本元素的类型 -->
							<xs:element name="书名" type="xs:string"></xs:element>
							<xs:element name="作者" type="xs:string"></xs:element>
							<xs:element name="价格" type="xs:decimal"></xs:element>
						</xs:sequence>
						<!-- 定义属性的名称、类型、默认值 -->
						<xs:attribute name="id" type="xs:integer" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>


<!-- 
schema vs dtd：
	1. 更灵活，一个xml文档中可以引入多个schema。
	2. 可以精确地指定某一个元素对应哪一个schema文件的规则
	3. schema值类型更多，有浮点、整数、字符串
 -->

=== SoraGrace/JavaLearning/TestUnit/src/com/fja/xml/xsd/bookshelf.xml
<?xml version="1.0" encoding="UTF-8"?>
<shelf:书架
	xmlns:shelf ="http://www.asdmd177.org/bookshelf"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.asdmd177.org/bookshelf ./bookshelf.xsd">
		<shelf:书 id="1">
			<shelf:书名>水浒传</shelf:书名>
			<shelf:作者>施耐庵</shelf:作者>
			<shelf:价格>32.99</shelf:价格>
		</shelf:书>
		
		<shelf:书 id="2">
			<shelf:书名>红楼梦</shelf:书名>
			<shelf:作者>曹雪芹</shelf:作者>
			<shelf:价格>35.99</shelf:价格>
		</shelf:书>
</shelf:书架>



<!-- 
	xml中引入Schema：
		1.在根标签内部声明自定义的Schema，格式： xmlns:命名空间的名称=命名空间的别名
		2.在xsi:schemaLocation中指定自定义的schema文件，格式: xsi:schemaLocation=命名空间的别名+(空格)+scheam文件路径
		
	使用命名空间：
		<命名空间的名称:标签></命名空间的名称:标签> 例：<shelf:书架></shelf:书架>
		
	【注意】
	xmlns=命名空间的别名，定义默认的命名空间，所有的未添加命名空间的名称的标签都要按照这个默认命名空间的规则书写
 -->
